[versions]
kotlin = "2.2.0"
intellij-ide = "2024.3.5"
intellij-plugin = "2.10.5"
junit = "5.10.2"
changelog = "2.2.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-plugin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }

[libraries]
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
